# ئەم فایلە ڕێکخستنەکانی لینتەر دیاری دەکات

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated/**
  errors:
    unused_import: warning
    unused_local_variable: warning
    deprecated_member_use: warning

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - camel_case_types
    - prefer_final_fields